spring:
server:
  port: 2027
application:
    name: ringup-apigateway
cloud:
    gateway:
      routes:
      - id: ringup-client
        uri: lb://RINGUP-CLIENT
        predicates:
        - Path=/api/v1/contact/**  
        filters:
           - AuthenticationFilter     
        
      - id: auth-client
        uri: lb://AUTH
        predicates:
        - Path=/auth/**   
   
logging:
  file.name: logs/ringup-apigateway-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: "info"
    org.springframework.web: "debug"
    org.hibernate: "error"
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    